### ISSUE TITLE
type piracy of Base.schedule(t::Task)

### ISSUE THREAD

**Issue by rfourquet** [oolong-dev/OpenTelemetry.jl#32]
It makes me a bit nervous, and also prevents packages depending on `OpenTelemetryAPI` to have proper precompilation, getting the following warning if I don't put `__precompile__(false):
```
   ** incremental compilation may be fatally broken for this module **
```
Is there any plan on not relying on type piracy?

**Comment by findmyway** [comment]
I'd like to, but can't find an alternative to automatically pass `Context` info into nested tasks at the time. One possible solution is to create a dedicated field in the `Task` object, or at least allow executing some hooks when scheduling each task. (I guess this is worth creating an issue in Julia?)

<hr>

Some more words on type piracy here:

In `OpenTelemetry`, it [mentioned](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md) the [cross cutting concern](https://en.wikipedia.org/wiki/Cross-cutting_concern). This means that we may have to use type piracy for many *instrumentation implementations*. Otherwise, we need to modify the upstream packages directly to allow injecting customized logic, https://github.com/JuliaWeb/HTTP.jl/pull/608 for example.

**Comment by findmyway** [comment]
It seems a related issue is already opened: https://github.com/JuliaLang/julia/issues/35757

**Comment by raffopazzo** [comment]
I haven't taken a deep look at the code yet but would it be possible to at least move the type piracy outside of the API module? In my project I embed Julia in a C++ app and I implement a meter provider that passes measurements to the C++ layer so in cases like this there is no need for that code to be in the API module itself. Should the override be in SDK instead?

**Comment by findmyway** [comment]
> I haven't taken a deep look at the code yet but would it be possible to at least move the type piracy outside of the API module? ... Should the override be in SDK instead?

Thanks! That's a good suggestion. I think it is doable. I'll give it a try and do some tests.

**Comment by pankgeorg** [comment]
@lamdor brought up https://github.com/vchuravy/ScopedValues.jl (and the respective https://github.com/JuliaLang/julia/pull/50958 PR). These are inherited across tasks, so they could potentially serve this purpose.
